name: Keep Streamlit Awake

on:
  schedule:
    # 한국 시간 기준 매일 오전 9시(UTC 기준 0시)에 한 번씩 실행됩니다.
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: URL 접속 시도
        run: curl -s https://kdz8ro4tbw2pk2tjsvdgcf.streamlit.app/ > /dev/null
